<a href="https://colab.research.google.com/github/itsnaeema/ML_Project/blob/main/Loan2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#one hot encoding in classification model
import numpy as np
import pandas as pd
df=pd.read_csv('/content/LoanApprovalPrediction.csv')
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [ ]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [ ]:
df.tail()

Loan_ID  Gender Married Dependents Education Self_Employed  \
609  LP002978  Female      No          0  Graduate            No   
610  LP002979    Male     Yes         3+  Graduate            No   
611  LP002983    Male     Yes          1  Graduate            No   
612  LP002984    Male     Yes          2  Graduate            No   
613  LP002990  Female      No          0  Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N

In [ ]:
df.dtypes

Loan_ID               object
Gender                object
Married               object
Dependents            object
Education             object
Self_Employed         object
ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area         object
Loan_Status           object
dtype: object

In [ ]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [ ]:
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [ ]:
df.drop('Loan_ID',axis=1,inplace=True)

In [ ]:
#missing value
x=df['Gender'].mode() [0]
y=df['Married'].mode() [0]
z=df['Dependents'].mode() [0]
w=df['Education'].mode() [0]
h=df['Self_Employed'].mode() [0]
l=df['LoanAmount'].mean()
v=df['Loan_Amount_Term'].mean()
b=df['Credit_History'].mean()
df['Gender'].fillna(x,inplace=True)
df['Married'].fillna(y,inplace=True)
df['Dependents'].fillna(z,inplace=True)
df['Education'].fillna(w,inplace=True)
df['Self_Employed'].fillna(h,inplace=True)
df['LoanAmount'].fillna(l,inplace=True)
df['Loan_Amount_Term'].fillna(v,inplace=True)
df['Credit_History'].fillna(b,inplace=True)
df.isna().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [ ]:
x=df.iloc[:,:-1]
x

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0      Male      No          0      Graduate            No             5849   
1      Male     Yes          1      Graduate            No             4583   
2      Male     Yes          0      Graduate           Yes             3000   
3      Male     Yes          0  Not Graduate            No             2583   
4      Male      No          0      Graduate            No             6000   
..      ...     ...        ...           ...           ...              ...   
609  Female      No          0      Graduate            No             2900   
610    Male     Yes         3+      Graduate            No             4106   
611    Male     Yes          1      Graduate            No             8072   
612    Male     Yes          2      Graduate            No             7583   
613  Female      No          0      Graduate           Yes             4583   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                  0.0  146.412162             360.0             1.0   
1               1508.0  128.000000             360.0             1.0   
2                  0.0   66.000000             360.0             1.0   
3               2358.0  120.000000             360.0             1.0   
4                  0.0  141.000000             360.0             1.0   
..                 ...         ...               ...             ...   
609                0.0   71.000000             360.0             1.0   
610                0.0   40.000000             180.0             1.0   
611              240.0  253.000000             360.0             1.0   
612                0.0  187.000000             360.0             1.0   
613                0.0  133.000000             360.0             0.0   

    Property_Area  
0           Urban  
1           Rural  
2           Urban  
3           Urban  
4           Urban  
..            ...  
609         Rural  
610         Rural  
611         Urban  
612         Urban  
613     Semiurban  

[614 rows x 11 columns]

In [ ]:
y=df.iloc[:,-1]
y

0      Y
1      N
2      Y
3      Y
4      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 614, dtype: object

In [ ]:
#one Hot Encoding
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
col_trans=make_column_transformer((OneHotEncoder(handle_unknown='ignore'),['Gender','Married','Dependents','Education','Self_Employed','Property_Area']),remainder='passthrough')
x=col_trans.fit_transform(x)
x

array([[  0.        ,   1.        ,   1.        , ..., 146.41216216,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 128.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ...,  66.        ,
        360.        ,   1.        ],
       ...,
       [  0.        ,   1.        ,   0.        , ..., 253.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 187.        ,
        360.        ,   1.        ],
       [  1.        ,   0.        ,   1.        , ..., 133.        ,
        360.        ,   0.        ]])

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=42)
x_train

array([[  0.        ,   1.        ,   0.        , ..., 181.        ,
        360.        ,   0.        ],
       [  0.        ,   1.        ,   0.        , ..., 155.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   1.        , ..., 134.        ,
        360.        ,   1.        ],
       ...,
       [  1.        ,   0.        ,   1.        , ...,  30.        ,
        360.        ,   1.        ],
       [  1.        ,   0.        ,   0.        , ..., 146.41216216,
        240.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 146.41216216,
        360.        ,   1.        ]])

In [ ]:
x_train

array([[  0.        ,   1.        ,   0.        , ..., 181.        ,
        360.        ,   0.        ],
       [  0.        ,   1.        ,   0.        , ..., 155.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   1.        , ..., 134.        ,
        360.        ,   1.        ],
       ...,
       [  1.        ,   0.        ,   1.        , ...,  30.        ,
        360.        ,   1.        ],
       [  1.        ,   0.        ,   0.        , ..., 146.41216216,
        240.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 146.41216216,
        360.        ,   1.        ]])

In [ ]:
x_test

array([[  0.        ,   1.        ,   0.        , ..., 228.        ,
        360.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 130.        ,
        360.        ,   0.84219858],
       [  0.        ,   1.        ,   0.        , ..., 158.        ,
        360.        ,   1.        ],
       ...,
       [  0.        ,   1.        ,   0.        , ..., 187.        ,
        180.        ,   1.        ],
       [  0.        ,   1.        ,   0.        , ..., 139.        ,
        360.        ,   1.        ],
       [  1.        ,   0.        ,   0.        , ..., 105.        ,
        360.        ,   0.        ]])

In [ ]:
y_train

553    N
601    Y
261    Y
496    Y
529    Y
      ..
71     Y
106    Y
270    Y
435    Y
102    Y
Name: Loan_Status, Length: 429, dtype: object

In [ ]:
y_test

350    Y
377    Y
163    Y
609    Y
132    Y
      ..
380    Y
446    Y
144    Y
290    Y
353    N
Name: Loan_Status, Length: 185, dtype: object

In [ ]:
#normalization
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(x_train)
x_train=scaler.transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[-0.49343516,  0.49343516, -0.77507823, ...,  0.40368493,
         0.31151435, -2.46213899],
       [-0.49343516,  0.49343516, -0.77507823, ...,  0.09632945,
         0.31151435,  0.4400635 ],
       [-0.49343516,  0.49343516,  1.29019234, ..., -0.15191921,
         0.31151435,  0.4400635 ],
       ...,
       [ 2.02660871, -2.02660871,  1.29019234, ..., -1.38134113,
         0.31151435,  0.4400635 ],
       [ 2.02660871, -2.02660871, -0.77507823, ..., -0.00519051,
        -1.45037962,  0.4400635 ],
       [-0.49343516,  0.49343516, -0.77507823, ..., -0.00519051,
         0.31151435,  0.4400635 ]])

In [ ]:
x_test

array([[-0.49343516,  0.49343516, -0.77507823, ...,  0.95928907,
         0.31151435,  0.4400635 ],
       [-0.49343516,  0.49343516, -0.77507823, ..., -0.19920467,
         0.31151435, -0.01790817],
       [-0.49343516,  0.49343516, -0.77507823, ...,  0.13179354,
         0.31151435,  0.4400635 ],
       ...,
       [-0.49343516,  0.49343516, -0.77507823, ...,  0.47461312,
        -2.33132661,  0.4400635 ],
       [-0.49343516,  0.49343516, -0.77507823, ..., -0.09281238,
         0.31151435,  0.4400635 ],
       [ 2.02660871, -2.02660871, -0.77507823, ..., -0.49473878,
         0.31151435, -2.46213899]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,accuracy_score
knn=KNeighborsClassifier(n_neighbors=7)
base=GaussianNB()
model=SVC()
lst=[knn,base,model]

In [ ]:
for i in lst:
  print("model name is...",i)
  i.fit(x_train,y_train)
  print("prediction value...")
  y_pred=i.predict(x_test)
  print(y_pred)
  print("confusion matrix is..")
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy score is....")
  print(accuracy_score(y_test,y_pred))

model name is... KNeighborsClassifier(n_neighbors=7)
prediction value...
['Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'N'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y'
 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'N' 'Y' 'Y' 'N' 'Y' 'Y' 'Y' 'Y' 'N' 'Y'
 'Y' 'Y' 'Y' 'Y' 'N']
confusion matrix is..
[[ 17  48]
 [ 10 110]]
Accuracy score is....
0.6864864864864865
model name is... GaussianNB()
prediction value...
['Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y' 'Y